-- ─────────────────────────────────────────────────────────────────────────────
-- Cartas específicas por clase: caudillo, arcanista, sombra, domador
-- 5 cartas por clase × 5 rarezas = 100 cartas nuevas
-- Bonos más potentes que las universales, con penalizaciones fuertes
-- ─────────────────────────────────────────────────────────────────────────────

-- ── Columna de restricción de clase ─────────────────────────────────────────
ALTER TABLE public.skill_cards
  ADD COLUMN IF NOT EXISTS required_class text
  REFERENCES public.classes(id);

-- ═══════════════════════════════════════════════════════════════════════════════
-- CAUDILLO — Dominio cuerpo a cuerpo: ATQ/FUE/HP grandes, penaliza INT/AGI
-- ═══════════════════════════════════════════════════════════════════════════════

INSERT INTO public.skill_cards (name, card_category, rarity, required_class, bonuses, penalties, description) VALUES
-- Offense
('Ira del Caudillo',    'offense', 'common', 'caudillo',
  '[{"stat":"attack","value":14},{"stat":"strength","value":6}]',
  '[{"stat":"intelligence","value":10}]',
  'La furia del campo de batalla canalizada en cada golpe. La estrategia es para los débiles.'),
('Ira del Caudillo',    'offense', 'uncommon', 'caudillo',
  '[{"stat":"attack","value":14},{"stat":"strength","value":6}]',
  '[{"stat":"intelligence","value":10}]',
  'La furia del campo de batalla canalizada en cada golpe. La estrategia es para los débiles.'),
('Ira del Caudillo',    'offense', 'rare', 'caudillo',
  '[{"stat":"attack","value":14},{"stat":"strength","value":6}]',
  '[{"stat":"intelligence","value":10}]',
  'La furia del campo de batalla canalizada en cada golpe. La estrategia es para los débiles.'),
('Ira del Caudillo',    'offense', 'epic', 'caudillo',
  '[{"stat":"attack","value":14},{"stat":"strength","value":6}]',
  '[{"stat":"intelligence","value":10}]',
  'La furia del campo de batalla canalizada en cada golpe. La estrategia es para los débiles.'),
('Ira del Caudillo',    'offense', 'legendary', 'caudillo',
  '[{"stat":"attack","value":14},{"stat":"strength","value":6}]',
  '[{"stat":"intelligence","value":10}]',
  'La furia del campo de batalla canalizada en cada golpe. La estrategia es para los débiles.'),

-- Defense
('Voluntad de Hierro',  'defense', 'common', 'caudillo',
  '[{"stat":"defense","value":12},{"stat":"max_hp","value":30}]',
  '[{"stat":"agility","value":10},{"stat":"intelligence","value":5}]',
  'Inamovible como una fortaleza. La velocidad y la astucia son sacrificios menores.'),
('Voluntad de Hierro',  'defense', 'uncommon', 'caudillo',
  '[{"stat":"defense","value":12},{"stat":"max_hp","value":30}]',
  '[{"stat":"agility","value":10},{"stat":"intelligence","value":5}]',
  'Inamovible como una fortaleza. La velocidad y la astucia son sacrificios menores.'),
('Voluntad de Hierro',  'defense', 'rare', 'caudillo',
  '[{"stat":"defense","value":12},{"stat":"max_hp","value":30}]',
  '[{"stat":"agility","value":10},{"stat":"intelligence","value":5}]',
  'Inamovible como una fortaleza. La velocidad y la astucia son sacrificios menores.'),
('Voluntad de Hierro',  'defense', 'epic', 'caudillo',
  '[{"stat":"defense","value":12},{"stat":"max_hp","value":30}]',
  '[{"stat":"agility","value":10},{"stat":"intelligence","value":5}]',
  'Inamovible como una fortaleza. La velocidad y la astucia son sacrificios menores.'),
('Voluntad de Hierro',  'defense', 'legendary', 'caudillo',
  '[{"stat":"defense","value":12},{"stat":"max_hp","value":30}]',
  '[{"stat":"agility","value":10},{"stat":"intelligence","value":5}]',
  'Inamovible como una fortaleza. La velocidad y la astucia son sacrificios menores.'),

-- Hybrid offense/defense
('Coloso',              'hybrid', 'common', 'caudillo',
  '[{"stat":"strength","value":12},{"stat":"max_hp","value":20}]',
  '[{"stat":"agility","value":12}]',
  'Grande, lento y demoledor. Cada paso hace temblar el suelo.'),
('Coloso',              'hybrid', 'uncommon', 'caudillo',
  '[{"stat":"strength","value":12},{"stat":"max_hp","value":20}]',
  '[{"stat":"agility","value":12}]',
  'Grande, lento y demoledor. Cada paso hace temblar el suelo.'),
('Coloso',              'hybrid', 'rare', 'caudillo',
  '[{"stat":"strength","value":12},{"stat":"max_hp","value":20}]',
  '[{"stat":"agility","value":12}]',
  'Grande, lento y demoledor. Cada paso hace temblar el suelo.'),
('Coloso',              'hybrid', 'epic', 'caudillo',
  '[{"stat":"strength","value":12},{"stat":"max_hp","value":20}]',
  '[{"stat":"agility","value":12}]',
  'Grande, lento y demoledor. Cada paso hace temblar el suelo.'),
('Coloso',              'hybrid', 'legendary', 'caudillo',
  '[{"stat":"strength","value":12},{"stat":"max_hp","value":20}]',
  '[{"stat":"agility","value":12}]',
  'Grande, lento y demoledor. Cada paso hace temblar el suelo.'),

-- Equipment
('Maestro de Armas',    'equipment', 'common', 'caudillo',
  '[{"stat":"weapon_attack_amp","value":0.20},{"stat":"strength","value":5}]',
  '[{"stat":"intelligence","value":8},{"stat":"agility","value":5}]',
  'Conoce cada filo como la palma de su mano. Su arma es una extensión de su cuerpo.'),
('Maestro de Armas',    'equipment', 'uncommon', 'caudillo',
  '[{"stat":"weapon_attack_amp","value":0.20},{"stat":"strength","value":5}]',
  '[{"stat":"intelligence","value":8},{"stat":"agility","value":5}]',
  'Conoce cada filo como la palma de su mano. Su arma es una extensión de su cuerpo.'),
('Maestro de Armas',    'equipment', 'rare', 'caudillo',
  '[{"stat":"weapon_attack_amp","value":0.20},{"stat":"strength","value":5}]',
  '[{"stat":"intelligence","value":8},{"stat":"agility","value":5}]',
  'Conoce cada filo como la palma de su mano. Su arma es una extensión de su cuerpo.'),
('Maestro de Armas',    'equipment', 'epic', 'caudillo',
  '[{"stat":"weapon_attack_amp","value":0.20},{"stat":"strength","value":5}]',
  '[{"stat":"intelligence","value":8},{"stat":"agility","value":5}]',
  'Conoce cada filo como la palma de su mano. Su arma es una extensión de su cuerpo.'),
('Maestro de Armas',    'equipment', 'legendary', 'caudillo',
  '[{"stat":"weapon_attack_amp","value":0.20},{"stat":"strength","value":5}]',
  '[{"stat":"intelligence","value":8},{"stat":"agility","value":5}]',
  'Conoce cada filo como la palma de su mano. Su arma es una extensión de su cuerpo.'),

-- Offense pure
('Carga Brutal',        'offense', 'common', 'caudillo',
  '[{"stat":"attack","value":16}]',
  '[{"stat":"defense","value":10},{"stat":"agility","value":5}]',
  'Sin escudo, sin plan, sin miedo. Solo la carga.'),
('Carga Brutal',        'offense', 'uncommon', 'caudillo',
  '[{"stat":"attack","value":16}]',
  '[{"stat":"defense","value":10},{"stat":"agility","value":5}]',
  'Sin escudo, sin plan, sin miedo. Solo la carga.'),
('Carga Brutal',        'offense', 'rare', 'caudillo',
  '[{"stat":"attack","value":16}]',
  '[{"stat":"defense","value":10},{"stat":"agility","value":5}]',
  'Sin escudo, sin plan, sin miedo. Solo la carga.'),
('Carga Brutal',        'offense', 'epic', 'caudillo',
  '[{"stat":"attack","value":16}]',
  '[{"stat":"defense","value":10},{"stat":"agility","value":5}]',
  'Sin escudo, sin plan, sin miedo. Solo la carga.'),
('Carga Brutal',        'offense', 'legendary', 'caudillo',
  '[{"stat":"attack","value":16}]',
  '[{"stat":"defense","value":10},{"stat":"agility","value":5}]',
  'Sin escudo, sin plan, sin miedo. Solo la carga.');

-- ═══════════════════════════════════════════════════════════════════════════════
-- ARCANISTA — Poder mágico: INT enormes, amplificación, penaliza DEF/FUE
-- ═══════════════════════════════════════════════════════════════════════════════

INSERT INTO public.skill_cards (name, card_category, rarity, required_class, bonuses, penalties, description) VALUES
-- Offense (INT puro)
('Canalización Arcana', 'offense', 'common', 'arcanista',
  '[{"stat":"intelligence","value":16}]',
  '[{"stat":"defense","value":8},{"stat":"strength","value":6}]',
  'Toda la energía fluye hacia la mente. El cuerpo es solo un recipiente.'),
('Canalización Arcana', 'offense', 'uncommon', 'arcanista',
  '[{"stat":"intelligence","value":16}]',
  '[{"stat":"defense","value":8},{"stat":"strength","value":6}]',
  'Toda la energía fluye hacia la mente. El cuerpo es solo un recipiente.'),
('Canalización Arcana', 'offense', 'rare', 'arcanista',
  '[{"stat":"intelligence","value":16}]',
  '[{"stat":"defense","value":8},{"stat":"strength","value":6}]',
  'Toda la energía fluye hacia la mente. El cuerpo es solo un recipiente.'),
('Canalización Arcana', 'offense', 'epic', 'arcanista',
  '[{"stat":"intelligence","value":16}]',
  '[{"stat":"defense","value":8},{"stat":"strength","value":6}]',
  'Toda la energía fluye hacia la mente. El cuerpo es solo un recipiente.'),
('Canalización Arcana', 'offense', 'legendary', 'arcanista',
  '[{"stat":"intelligence","value":16}]',
  '[{"stat":"defense","value":8},{"stat":"strength","value":6}]',
  'Toda la energía fluye hacia la mente. El cuerpo es solo un recipiente.'),

-- Hybrid INT+ATQ
('Tormenta Mística',    'hybrid', 'common', 'arcanista',
  '[{"stat":"attack","value":10},{"stat":"intelligence","value":10}]',
  '[{"stat":"defense","value":10},{"stat":"max_hp","value":15}]',
  'Rayos y fuego. Destrucción pura con un coste físico devastador.'),
('Tormenta Mística',    'hybrid', 'uncommon', 'arcanista',
  '[{"stat":"attack","value":10},{"stat":"intelligence","value":10}]',
  '[{"stat":"defense","value":10},{"stat":"max_hp","value":15}]',
  'Rayos y fuego. Destrucción pura con un coste físico devastador.'),
('Tormenta Mística',    'hybrid', 'rare', 'arcanista',
  '[{"stat":"attack","value":10},{"stat":"intelligence","value":10}]',
  '[{"stat":"defense","value":10},{"stat":"max_hp","value":15}]',
  'Rayos y fuego. Destrucción pura con un coste físico devastador.'),
('Tormenta Mística',    'hybrid', 'epic', 'arcanista',
  '[{"stat":"attack","value":10},{"stat":"intelligence","value":10}]',
  '[{"stat":"defense","value":10},{"stat":"max_hp","value":15}]',
  'Rayos y fuego. Destrucción pura con un coste físico devastador.'),
('Tormenta Mística',    'hybrid', 'legendary', 'arcanista',
  '[{"stat":"attack","value":10},{"stat":"intelligence","value":10}]',
  '[{"stat":"defense","value":10},{"stat":"max_hp","value":15}]',
  'Rayos y fuego. Destrucción pura con un coste físico devastador.'),

-- Equipment (amplificación de runas)
('Resonancia Rúnica',   'equipment', 'common', 'arcanista',
  '[{"stat":"enchantment_amp","value":0.15},{"stat":"intelligence","value":6}]',
  '[{"stat":"strength","value":8},{"stat":"defense","value":5}]',
  'Las runas vibran con más fuerza en manos arcanas. El cuerpo paga el precio.'),
('Resonancia Rúnica',   'equipment', 'uncommon', 'arcanista',
  '[{"stat":"enchantment_amp","value":0.15},{"stat":"intelligence","value":6}]',
  '[{"stat":"strength","value":8},{"stat":"defense","value":5}]',
  'Las runas vibran con más fuerza en manos arcanas. El cuerpo paga el precio.'),
('Resonancia Rúnica',   'equipment', 'rare', 'arcanista',
  '[{"stat":"enchantment_amp","value":0.15},{"stat":"intelligence","value":6}]',
  '[{"stat":"strength","value":8},{"stat":"defense","value":5}]',
  'Las runas vibran con más fuerza en manos arcanas. El cuerpo paga el precio.'),
('Resonancia Rúnica',   'equipment', 'epic', 'arcanista',
  '[{"stat":"enchantment_amp","value":0.15},{"stat":"intelligence","value":6}]',
  '[{"stat":"strength","value":8},{"stat":"defense","value":5}]',
  'Las runas vibran con más fuerza en manos arcanas. El cuerpo paga el precio.'),
('Resonancia Rúnica',   'equipment', 'legendary', 'arcanista',
  '[{"stat":"enchantment_amp","value":0.15},{"stat":"intelligence","value":6}]',
  '[{"stat":"strength","value":8},{"stat":"defense","value":5}]',
  'Las runas vibran con más fuerza en manos arcanas. El cuerpo paga el precio.'),

-- Defense (HP mágico)
('Barrera Arcana',      'defense', 'common', 'arcanista',
  '[{"stat":"max_hp","value":35},{"stat":"intelligence","value":5}]',
  '[{"stat":"strength","value":10},{"stat":"agility","value":5}]',
  'Un escudo invisible de energía pura. El cuerpo se debilita, pero la mente protege.'),
('Barrera Arcana',      'defense', 'uncommon', 'arcanista',
  '[{"stat":"max_hp","value":35},{"stat":"intelligence","value":5}]',
  '[{"stat":"strength","value":10},{"stat":"agility","value":5}]',
  'Un escudo invisible de energía pura. El cuerpo se debilita, pero la mente protege.'),
('Barrera Arcana',      'defense', 'rare', 'arcanista',
  '[{"stat":"max_hp","value":35},{"stat":"intelligence","value":5}]',
  '[{"stat":"strength","value":10},{"stat":"agility","value":5}]',
  'Un escudo invisible de energía pura. El cuerpo se debilita, pero la mente protege.'),
('Barrera Arcana',      'defense', 'epic', 'arcanista',
  '[{"stat":"max_hp","value":35},{"stat":"intelligence","value":5}]',
  '[{"stat":"strength","value":10},{"stat":"agility","value":5}]',
  'Un escudo invisible de energía pura. El cuerpo se debilita, pero la mente protege.'),
('Barrera Arcana',      'defense', 'legendary', 'arcanista',
  '[{"stat":"max_hp","value":35},{"stat":"intelligence","value":5}]',
  '[{"stat":"strength","value":10},{"stat":"agility","value":5}]',
  'Un escudo invisible de energía pura. El cuerpo se debilita, pero la mente protege.'),

-- Mobility (INT + AGI)
('Mente Veloz',         'mobility', 'common', 'arcanista',
  '[{"stat":"intelligence","value":12},{"stat":"agility","value":6}]',
  '[{"stat":"defense","value":12},{"stat":"max_hp","value":10}]',
  'Piensa rápido, se mueve rápido. Pero un solo golpe puede ser el último.'),
('Mente Veloz',         'mobility', 'uncommon', 'arcanista',
  '[{"stat":"intelligence","value":12},{"stat":"agility","value":6}]',
  '[{"stat":"defense","value":12},{"stat":"max_hp","value":10}]',
  'Piensa rápido, se mueve rápido. Pero un solo golpe puede ser el último.'),
('Mente Veloz',         'mobility', 'rare', 'arcanista',
  '[{"stat":"intelligence","value":12},{"stat":"agility","value":6}]',
  '[{"stat":"defense","value":12},{"stat":"max_hp","value":10}]',
  'Piensa rápido, se mueve rápido. Pero un solo golpe puede ser el último.'),
('Mente Veloz',         'mobility', 'epic', 'arcanista',
  '[{"stat":"intelligence","value":12},{"stat":"agility","value":6}]',
  '[{"stat":"defense","value":12},{"stat":"max_hp","value":10}]',
  'Piensa rápido, se mueve rápido. Pero un solo golpe puede ser el último.'),
('Mente Veloz',         'mobility', 'legendary', 'arcanista',
  '[{"stat":"intelligence","value":12},{"stat":"agility","value":6}]',
  '[{"stat":"defense","value":12},{"stat":"max_hp","value":10}]',
  'Piensa rápido, se mueve rápido. Pero un solo golpe puede ser el último.');

-- ═══════════════════════════════════════════════════════════════════════════════
-- SOMBRA — Velocidad y precisión: AGI/ATQ altos, drop rate, penaliza HP/DEF
-- ═══════════════════════════════════════════════════════════════════════════════

INSERT INTO public.skill_cards (name, card_category, rarity, required_class, bonuses, penalties, description) VALUES
-- Offense (ATQ + AGI)
('Golpe Letal',         'offense', 'common', 'sombra',
  '[{"stat":"attack","value":14},{"stat":"agility","value":6}]',
  '[{"stat":"max_hp","value":25},{"stat":"defense","value":5}]',
  'Un solo corte perfecto. No hay segunda oportunidad, ni para el enemigo ni para ti.'),
('Golpe Letal',         'offense', 'uncommon', 'sombra',
  '[{"stat":"attack","value":14},{"stat":"agility","value":6}]',
  '[{"stat":"max_hp","value":25},{"stat":"defense","value":5}]',
  'Un solo corte perfecto. No hay segunda oportunidad, ni para el enemigo ni para ti.'),
('Golpe Letal',         'offense', 'rare', 'sombra',
  '[{"stat":"attack","value":14},{"stat":"agility","value":6}]',
  '[{"stat":"max_hp","value":25},{"stat":"defense","value":5}]',
  'Un solo corte perfecto. No hay segunda oportunidad, ni para el enemigo ni para ti.'),
('Golpe Letal',         'offense', 'epic', 'sombra',
  '[{"stat":"attack","value":14},{"stat":"agility","value":6}]',
  '[{"stat":"max_hp","value":25},{"stat":"defense","value":5}]',
  'Un solo corte perfecto. No hay segunda oportunidad, ni para el enemigo ni para ti.'),
('Golpe Letal',         'offense', 'legendary', 'sombra',
  '[{"stat":"attack","value":14},{"stat":"agility","value":6}]',
  '[{"stat":"max_hp","value":25},{"stat":"defense","value":5}]',
  'Un solo corte perfecto. No hay segunda oportunidad, ni para el enemigo ni para ti.'),

-- Mobility (AGI pura)
('Paso de Sombra',      'mobility', 'common', 'sombra',
  '[{"stat":"agility","value":16}]',
  '[{"stat":"strength","value":8},{"stat":"max_hp","value":15}]',
  'Invisible, silencioso, inalcanzable. El cuerpo se vuelve ligero como una pluma.'),
('Paso de Sombra',      'mobility', 'uncommon', 'sombra',
  '[{"stat":"agility","value":16}]',
  '[{"stat":"strength","value":8},{"stat":"max_hp","value":15}]',
  'Invisible, silencioso, inalcanzable. El cuerpo se vuelve ligero como una pluma.'),
('Paso de Sombra',      'mobility', 'rare', 'sombra',
  '[{"stat":"agility","value":16}]',
  '[{"stat":"strength","value":8},{"stat":"max_hp","value":15}]',
  'Invisible, silencioso, inalcanzable. El cuerpo se vuelve ligero como una pluma.'),
('Paso de Sombra',      'mobility', 'epic', 'sombra',
  '[{"stat":"agility","value":16}]',
  '[{"stat":"strength","value":8},{"stat":"max_hp","value":15}]',
  'Invisible, silencioso, inalcanzable. El cuerpo se vuelve ligero como una pluma.'),
('Paso de Sombra',      'mobility', 'legendary', 'sombra',
  '[{"stat":"agility","value":16}]',
  '[{"stat":"strength","value":8},{"stat":"max_hp","value":15}]',
  'Invisible, silencioso, inalcanzable. El cuerpo se vuelve ligero como una pluma.'),

-- Equipment (drop rate)
('Ojo de Ladrón',       'equipment', 'common', 'sombra',
  '[{"stat":"item_drop_rate","value":0.08},{"stat":"agility","value":5}]',
  '[{"stat":"defense","value":8},{"stat":"max_hp","value":10}]',
  'Ve lo que otros no ven. Cada cofre, cada bolsillo, cada rendija esconde un tesoro.'),
('Ojo de Ladrón',       'equipment', 'uncommon', 'sombra',
  '[{"stat":"item_drop_rate","value":0.08},{"stat":"agility","value":5}]',
  '[{"stat":"defense","value":8},{"stat":"max_hp","value":10}]',
  'Ve lo que otros no ven. Cada cofre, cada bolsillo, cada rendija esconde un tesoro.'),
('Ojo de Ladrón',       'equipment', 'rare', 'sombra',
  '[{"stat":"item_drop_rate","value":0.08},{"stat":"agility","value":5}]',
  '[{"stat":"defense","value":8},{"stat":"max_hp","value":10}]',
  'Ve lo que otros no ven. Cada cofre, cada bolsillo, cada rendija esconde un tesoro.'),
('Ojo de Ladrón',       'equipment', 'epic', 'sombra',
  '[{"stat":"item_drop_rate","value":0.08},{"stat":"agility","value":5}]',
  '[{"stat":"defense","value":8},{"stat":"max_hp","value":10}]',
  'Ve lo que otros no ven. Cada cofre, cada bolsillo, cada rendija esconde un tesoro.'),
('Ojo de Ladrón',       'equipment', 'legendary', 'sombra',
  '[{"stat":"item_drop_rate","value":0.08},{"stat":"agility","value":5}]',
  '[{"stat":"defense","value":8},{"stat":"max_hp","value":10}]',
  'Ve lo que otros no ven. Cada cofre, cada bolsillo, cada rendija esconde un tesoro.'),

-- Hybrid (ATQ + AGI extremo, glass cannon)
('Danza Mortal',        'hybrid', 'common', 'sombra',
  '[{"stat":"attack","value":12},{"stat":"agility","value":10}]',
  '[{"stat":"defense","value":12},{"stat":"max_hp","value":20}]',
  'Mata bailando. Cada movimiento es un corte, cada corte es mortal. Pero un tropiezo es la muerte.'),
('Danza Mortal',        'hybrid', 'uncommon', 'sombra',
  '[{"stat":"attack","value":12},{"stat":"agility","value":10}]',
  '[{"stat":"defense","value":12},{"stat":"max_hp","value":20}]',
  'Mata bailando. Cada movimiento es un corte, cada corte es mortal. Pero un tropiezo es la muerte.'),
('Danza Mortal',        'hybrid', 'rare', 'sombra',
  '[{"stat":"attack","value":12},{"stat":"agility","value":10}]',
  '[{"stat":"defense","value":12},{"stat":"max_hp","value":20}]',
  'Mata bailando. Cada movimiento es un corte, cada corte es mortal. Pero un tropiezo es la muerte.'),
('Danza Mortal',        'hybrid', 'epic', 'sombra',
  '[{"stat":"attack","value":12},{"stat":"agility","value":10}]',
  '[{"stat":"defense","value":12},{"stat":"max_hp","value":20}]',
  'Mata bailando. Cada movimiento es un corte, cada corte es mortal. Pero un tropiezo es la muerte.'),
('Danza Mortal',        'hybrid', 'legendary', 'sombra',
  '[{"stat":"attack","value":12},{"stat":"agility","value":10}]',
  '[{"stat":"defense","value":12},{"stat":"max_hp","value":20}]',
  'Mata bailando. Cada movimiento es un corte, cada corte es mortal. Pero un tropiezo es la muerte.'),

-- Defense (evasión = AGI defensiva)
('Reflejos Oscuros',    'defense', 'common', 'sombra',
  '[{"stat":"agility","value":10},{"stat":"defense","value":6}]',
  '[{"stat":"strength","value":10},{"stat":"max_hp","value":10}]',
  'No necesita armadura quien esquiva todo. Pero cuando falla... duele.'),
('Reflejos Oscuros',    'defense', 'uncommon', 'sombra',
  '[{"stat":"agility","value":10},{"stat":"defense","value":6}]',
  '[{"stat":"strength","value":10},{"stat":"max_hp","value":10}]',
  'No necesita armadura quien esquiva todo. Pero cuando falla... duele.'),
('Reflejos Oscuros',    'defense', 'rare', 'sombra',
  '[{"stat":"agility","value":10},{"stat":"defense","value":6}]',
  '[{"stat":"strength","value":10},{"stat":"max_hp","value":10}]',
  'No necesita armadura quien esquiva todo. Pero cuando falla... duele.'),
('Reflejos Oscuros',    'defense', 'epic', 'sombra',
  '[{"stat":"agility","value":10},{"stat":"defense","value":6}]',
  '[{"stat":"strength","value":10},{"stat":"max_hp","value":10}]',
  'No necesita armadura quien esquiva todo. Pero cuando falla... duele.'),
('Reflejos Oscuros',    'defense', 'legendary', 'sombra',
  '[{"stat":"agility","value":10},{"stat":"defense","value":6}]',
  '[{"stat":"strength","value":10},{"stat":"max_hp","value":10}]',
  'No necesita armadura quien esquiva todo. Pero cuando falla... duele.');

-- ═══════════════════════════════════════════════════════════════════════════════
-- DOMADOR — Versatilidad: bonos equilibrados, HP, durabilidad, sinergias
-- ═══════════════════════════════════════════════════════════════════════════════

INSERT INTO public.skill_cards (name, card_category, rarity, required_class, bonuses, penalties, description) VALUES
-- Hybrid (triple stat)
('Vínculo Salvaje',     'hybrid', 'common', 'domador',
  '[{"stat":"strength","value":7},{"stat":"agility","value":7},{"stat":"intelligence","value":7}]',
  '[{"stat":"attack","value":10}]',
  'La conexión con la naturaleza fortalece cuerpo, mente y espíritu. Pero el instinto asesino se apaga.'),
('Vínculo Salvaje',     'hybrid', 'uncommon', 'domador',
  '[{"stat":"strength","value":7},{"stat":"agility","value":7},{"stat":"intelligence","value":7}]',
  '[{"stat":"attack","value":10}]',
  'La conexión con la naturaleza fortalece cuerpo, mente y espíritu. Pero el instinto asesino se apaga.'),
('Vínculo Salvaje',     'hybrid', 'rare', 'domador',
  '[{"stat":"strength","value":7},{"stat":"agility","value":7},{"stat":"intelligence","value":7}]',
  '[{"stat":"attack","value":10}]',
  'La conexión con la naturaleza fortalece cuerpo, mente y espíritu. Pero el instinto asesino se apaga.'),
('Vínculo Salvaje',     'hybrid', 'epic', 'domador',
  '[{"stat":"strength","value":7},{"stat":"agility","value":7},{"stat":"intelligence","value":7}]',
  '[{"stat":"attack","value":10}]',
  'La conexión con la naturaleza fortalece cuerpo, mente y espíritu. Pero el instinto asesino se apaga.'),
('Vínculo Salvaje',     'hybrid', 'legendary', 'domador',
  '[{"stat":"strength","value":7},{"stat":"agility","value":7},{"stat":"intelligence","value":7}]',
  '[{"stat":"attack","value":10}]',
  'La conexión con la naturaleza fortalece cuerpo, mente y espíritu. Pero el instinto asesino se apaga.'),

-- Defense (HP + durabilidad)
('Piel de Bestia',      'defense', 'common', 'domador',
  '[{"stat":"max_hp","value":30},{"stat":"defense","value":8}]',
  '[{"stat":"attack","value":8},{"stat":"intelligence","value":5}]',
  'La piel se endurece como la de las bestias que domina. Pierde filo, gana resistencia.'),
('Piel de Bestia',      'defense', 'uncommon', 'domador',
  '[{"stat":"max_hp","value":30},{"stat":"defense","value":8}]',
  '[{"stat":"attack","value":8},{"stat":"intelligence","value":5}]',
  'La piel se endurece como la de las bestias que domina. Pierde filo, gana resistencia.'),
('Piel de Bestia',      'defense', 'rare', 'domador',
  '[{"stat":"max_hp","value":30},{"stat":"defense","value":8}]',
  '[{"stat":"attack","value":8},{"stat":"intelligence","value":5}]',
  'La piel se endurece como la de las bestias que domina. Pierde filo, gana resistencia.'),
('Piel de Bestia',      'defense', 'epic', 'domador',
  '[{"stat":"max_hp","value":30},{"stat":"defense","value":8}]',
  '[{"stat":"attack","value":8},{"stat":"intelligence","value":5}]',
  'La piel se endurece como la de las bestias que domina. Pierde filo, gana resistencia.'),
('Piel de Bestia',      'defense', 'legendary', 'domador',
  '[{"stat":"max_hp","value":30},{"stat":"defense","value":8}]',
  '[{"stat":"attack","value":8},{"stat":"intelligence","value":5}]',
  'La piel se endurece como la de las bestias que domina. Pierde filo, gana resistencia.'),

-- Equipment (durabilidad + balanced)
('Custodio Natural',    'equipment', 'common', 'domador',
  '[{"stat":"durability_loss","value":-3},{"stat":"defense","value":5}]',
  '[{"stat":"attack","value":7},{"stat":"agility","value":5}]',
  'La naturaleza protege lo que le pertenece. El equipo dura más, pero el filo se embota.'),
('Custodio Natural',    'equipment', 'uncommon', 'domador',
  '[{"stat":"durability_loss","value":-3},{"stat":"defense","value":5}]',
  '[{"stat":"attack","value":7},{"stat":"agility","value":5}]',
  'La naturaleza protege lo que le pertenece. El equipo dura más, pero el filo se embota.'),
('Custodio Natural',    'equipment', 'rare', 'domador',
  '[{"stat":"durability_loss","value":-3},{"stat":"defense","value":5}]',
  '[{"stat":"attack","value":7},{"stat":"agility","value":5}]',
  'La naturaleza protege lo que le pertenece. El equipo dura más, pero el filo se embota.'),
('Custodio Natural',    'equipment', 'epic', 'domador',
  '[{"stat":"durability_loss","value":-3},{"stat":"defense","value":5}]',
  '[{"stat":"attack","value":7},{"stat":"agility","value":5}]',
  'La naturaleza protege lo que le pertenece. El equipo dura más, pero el filo se embota.'),
('Custodio Natural',    'equipment', 'legendary', 'domador',
  '[{"stat":"durability_loss","value":-3},{"stat":"defense","value":5}]',
  '[{"stat":"attack","value":7},{"stat":"agility","value":5}]',
  'La naturaleza protege lo que le pertenece. El equipo dura más, pero el filo se embota.'),

-- Offense (ATQ + FUE equilibrado)
('Furia Bestial',       'offense', 'common', 'domador',
  '[{"stat":"attack","value":10},{"stat":"strength","value":8}]',
  '[{"stat":"intelligence","value":10},{"stat":"agility","value":5}]',
  'Canaliza la rabia animal. Golpea fuerte, pero pierde la cabeza.'),
('Furia Bestial',       'offense', 'uncommon', 'domador',
  '[{"stat":"attack","value":10},{"stat":"strength","value":8}]',
  '[{"stat":"intelligence","value":10},{"stat":"agility","value":5}]',
  'Canaliza la rabia animal. Golpea fuerte, pero pierde la cabeza.'),
('Furia Bestial',       'offense', 'rare', 'domador',
  '[{"stat":"attack","value":10},{"stat":"strength","value":8}]',
  '[{"stat":"intelligence","value":10},{"stat":"agility","value":5}]',
  'Canaliza la rabia animal. Golpea fuerte, pero pierde la cabeza.'),
('Furia Bestial',       'offense', 'epic', 'domador',
  '[{"stat":"attack","value":10},{"stat":"strength","value":8}]',
  '[{"stat":"intelligence","value":10},{"stat":"agility","value":5}]',
  'Canaliza la rabia animal. Golpea fuerte, pero pierde la cabeza.'),
('Furia Bestial',       'offense', 'legendary', 'domador',
  '[{"stat":"attack","value":10},{"stat":"strength","value":8}]',
  '[{"stat":"intelligence","value":10},{"stat":"agility","value":5}]',
  'Canaliza la rabia animal. Golpea fuerte, pero pierde la cabeza.'),

-- Mobility (AGI + INT equilibrado)
('Instinto Animal',     'mobility', 'common', 'domador',
  '[{"stat":"agility","value":8},{"stat":"intelligence","value":8}]',
  '[{"stat":"defense","value":8},{"stat":"strength","value":5}]',
  'Los sentidos del depredador. Ve, oye y reacciona antes que nadie.'),
('Instinto Animal',     'mobility', 'uncommon', 'domador',
  '[{"stat":"agility","value":8},{"stat":"intelligence","value":8}]',
  '[{"stat":"defense","value":8},{"stat":"strength","value":5}]',
  'Los sentidos del depredador. Ve, oye y reacciona antes que nadie.'),
('Instinto Animal',     'mobility', 'rare', 'domador',
  '[{"stat":"agility","value":8},{"stat":"intelligence","value":8}]',
  '[{"stat":"defense","value":8},{"stat":"strength","value":5}]',
  'Los sentidos del depredador. Ve, oye y reacciona antes que nadie.'),
('Instinto Animal',     'mobility', 'epic', 'domador',
  '[{"stat":"agility","value":8},{"stat":"intelligence","value":8}]',
  '[{"stat":"defense","value":8},{"stat":"strength","value":5}]',
  'Los sentidos del depredador. Ve, oye y reacciona antes que nadie.'),
('Instinto Animal',     'mobility', 'legendary', 'domador',
  '[{"stat":"agility","value":8},{"stat":"intelligence","value":8}]',
  '[{"stat":"defense","value":8},{"stat":"strength","value":5}]',
  'Los sentidos del depredador. Ve, oye y reacciona antes que nadie.');
