/** Constantes de la API. La lógica de juego vive en src/lib/gameConstants.js */

// Re-exportar para que los endpoints no necesiten conocer la ruta completa
export {
  UNLOCK_TRIGGERS,
  INVENTORY_BASE_LIMIT,
  BAG_SLOTS_PER_UPGRADE,
  BAG_UPGRADE_COSTS,
  BAG_MAX_UPGRADES,
  HERO_SLOT_REQUIREMENTS,
  HERO_SLOT_CLASS,
  CLASS_TRAINING_STATS,
  MAX_POTION_STACK,
  POTION_CRAFT_DURATION_MS,
  TRAINING_ROOM_STATS,
  TACTIC_SLOT_COUNT,
  TACTIC_MAX_LEVEL,
  TACTIC_SWAP_COST,
  REPAIR_COST_TABLE,
  REPAIR_IRON_BY_RARITY,
  REPAIR_IRON_SLOT_MULT,
  DISMANTLE_GOLD_TABLE,
  DISMANTLE_TABLE,
  DISMANTLE_RUNE_BONUS,
  CRAFTING_SLOTS_BASE,
  LAB_INVENTORY_BASE,
  LAB_INVENTORY_PER_UPGRADE,
  LAB_INVENTORY_MAX_UPGRADES,
  LAB_INVENTORY_UPGRADE_COSTS,
} from '../src/lib/gameConstants.js'

